### ISSUE TITLE
Low Organization Cohesion

### ISSUE THREAD

**Issue by krispynaaan** [tamu-tt/tasks#2]
Throughout the Fall 2023 and Spring 2024 semesters, it was noticed that many of the teams struggled with staying together as a team. This often led to a severe lack of motivation for team members and resulted in some team members not doing their assigned tasks. This issue is opened to address possible remedies to this problem.

**Comment by StevensonGM** [comment]
This is being addressed through the increased cadence and restructuring of general meetings to once a week and only being half lecture and half social. This will be supplemented by participation in The Big Event.

Ways this can be addressed further:
Charitable fundraising as an org (Kyle Field cleanup/concession stand running)
Purposefully planned social events
More social media coverage of our teams!
