### ISSUE TITLE
Initial Team Meeting Checklist Template

### ISSUE THREAD

**Issue by Hybrinter** [tamu-tt/tasks#25]
Create a checklist template for the initial team meeting that outlines the talking points for the assigned CTC and any other officer present.

[Initial Team Meeting Checklist Template](https://docs.google.com/document/d/1L2cxSKtr2PTDk0egXBxRJT9UEVcuNd2OlHoghRR5kT8/edit?usp=drive_link)

**Comment by krispynaaan** [comment]
@Hybrinter Checklist Complete, close this issue on your approval.
